name: Build

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python3 -m pip install -U pip setuptools
    - name: Install
      run: |
        python3 -m pip install --user .
        cd /tmp
        python3 -m pypcode -l
        echo "McA5xnYRSInBg+EfigwKMAwHSP/A6+vD" | base64 -d > test-x64.bin
        python -m pypcode x86:LE:64:default test-x64.bin
